### ISSUE TITLE
Compress Function Failing Size Test

### ISSUE THREAD

**Issue by aldenchen** [UBC-MDS/image-compression-toolkit-python#36]
- The test that checks whether the image is compressed to the right size is failing
- Probably need to adjust the calculation in the test, but not sure how PNG does compression

**Comment by adityashrm21** [comment]
Can you post more about the example that you are using for the test?

**Comment by aldenchen** [comment]
`compressed_img = compress(img_path, 3)`
`assert image_size(compressed_img) < 4/8 * image_size(img_path)`

This line causes the test to fail. The compressed image is bigger than 4/8 of the original. The image being used is called `test_image_1718.png`.

Original size: 1221
Compressed size, b = 3: 770

**Comment by adityashrm21** [comment]
I think we can increase the error margin a little bit as skimage.io.imsave might be saving some more information along with the image (which I am suspecting to be of a small size). That is why the tests are working on large images but failing on small ones.

**Comment by aldenchen** [comment]
Increased margin of error in tests.
