### ISSUE TITLE
Crop Tests Failing

### ISSUE THREAD

**Issue by aldenchen** [UBC-MDS/image-compression-toolkit-python#37]
- The crop function fails the `test_crop_value` test and the `test_crop_shape` test

**Comment by aldenchen** [comment]
Looks like the issue is with line 33 in the `crop.py` file - a variable `image` is referenced before it is defined.

I think you just need to replace `image` with `imread(img_path)` in line 33

**Comment by aldenchen** [comment]
I think you just need to replace `image` with `imread(img_path)` in line 33

**Comment by aldenchen** [comment]
Also, I noticed you are checking  `H == int(-1e30) or W==int(-1e30)` in line 31. It's not necessary since  H and W are already being compared against zero and the image shape. I just used those numbers in the tests to test for a big positive/negative number.

**Comment by Sayanti86** [comment]
Fixed all .
