### ISSUE TITLE
Update Compress Function

### ISSUE THREAD

**Issue by aldenchen** [UBC-MDS/image-compression-toolkit-python#48]
Update compress function to handle images that are already compressed  
1. Compare size of image compressed to the `b` specified by the user against the original image size. If compressed is smaller, return compressed.  
2.  Otherwise, compare size of the image compressed to `b = 1` against the original image size. If the image compressed to `b=1` is still bigger than original, tell user the image cannot be compressed any more. Else, tell the user to choose a smaller `b`.

**Comment by adityashrm21** [comment]
done
